/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#ifndef SWIG_test_WRAP_H_
#define SWIG_test_WRAP_H_


#ifndef SWIGIMPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGDLLIMPORT
#   else
#     define SWIGDLLIMPORT __declspec(dllimport)
#   endif
# else
#   define SWIGDLLIMPORT
# endif
# define SWIGIMPORT extern SWIGDLLIMPORT
#endif

#include <stddef.h>


typedef struct SwigObj SwigObj;

typedef struct SwigObj_wi_Application wi_Application;

#ifdef __cplusplus
extern "C" {
#endif

SWIGIMPORT void wi_Application_Initialize(wi_Application* carg1);

SWIGIMPORT wi_Application* wi_Application_new();

SWIGIMPORT void wi_Application_delete(wi_Application* carg1);

SWIGIMPORT void wi_arguments_Parse(int carg1, char ** carg2);

#ifdef __cplusplus
}
#endif


#endif /* SWIG_test_WRAP_H_ */
